on:
  pull_request:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      path: ./test/terraform
    secrets: inherit
