on:
  pull_request:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:   
  linting:
    uses: './github/workflows/tf-lint.yml'
    with:
      path: ./test/terraform
    secrets:
      token: ${{ env.GITHUB_TOKEN }}

  security:
    uses: './github/workflows/tf-security.yml'
    with:
      path: ./test/terraform
    secrets:
      token: ${{ env.GITHUB_TOKEN }}

  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      path: ./test/terraform
    secrets:
      token: ${{ env.GITHUB_TOKEN }}
