name: Terraform Linting
on:
  workflow_call:
    inputs:
      path:
        description: The path to the working directory
        required: false
        type: string
        default: '.'
      terraform_version:
        description: The version of terraform to use. Defaults to the latest
        required: false
        type: string
        default: 'latest'
      terraform_workspace:
        description: Name of the terraform workspace.
        required: false
        type: string
        default: 'default'
      variables:
        description: Variables to pass to terraform
        required: false
        type: string
        default: ''
    secrets:
      token:
        description: "GitHub token to use for authenticating with this instance of GitHub. The token needs the `content: write` permission."
        required: false
        default: ${{ github.token }}

jobs:
  linting:
    name: Terraform Linting
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.path }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ inputs.terraform_version }}

      - name: 'Terraform Format'
        run: terraform fmt -write=true -recursive

      - name: 'TFLint'
        uses: pauloconnor/tflint-action@v0.0.2 
        with:
          tflint_path: ${{ inputs.path }}
          tflint_changed_only: false
          tflint_extra_options: --output json
          tflint_enabled_rules:
            terraform_required_providers
            terraform_standard_module_structure
          tflint_disabled_rules:
            terraform_deprecated_interpolation

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply linting changes
          status_options: '--untracked-files=no'

