name: Terraform Linting
on:
  workflow_call:
    inputs:
      path:
        description: The path to the working directory
        required: false
        type: string
        default: '.'
      terraform_version:
        description: The version of terraform to use. Defaults to the latest
        required: false
        type: string
        default: 'latest'
      terraform_workspace:
        description: Name of the terraform workspace.
        required: false
        type: string
        default: 'default'
      variables:
        description: Variables to pass to terraform
        required: false
        type: string
        default: ''

jobs:
  linting:
    name: Terraform Linting
    runs-on: unbuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: 'Terraform Format'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ inputs.terraform_version }}
          tf_actions_subcommand: 'fmt'
          tf_actions_working_dir: ${{ inputs.path }}
          tf_actions_comment: true
          tf_actions_fmt_write: true
          args: '${{ inputs.variables }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_WORKSPACE: ${{ inputs.terraform_workspace }} 

      - name: 'TFLint'
        uses: pauloconnor/tflint-action@v0.0.2 
        with:
          tflint_path: ${{ inputs.path }}
          tflint_changed_only: false
          tflint_extra_options: --output json
          tflint_enabled_rules:
            terraform_required_providers
            terraform_standard_module_structure
          tflint_disabled_rules:
            terraform_deprecated_interpolation

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply linting changes
          status_options: '--untracked-files=no'

