name: Terraform Security Checks
description: Runs static code analysis against terraform workspaces to look for security issues
on:
  workflow_call:
    inputs:
      path:
        description: The path to the working directory
        required: false
        type: string
        default: '.'
      tfsec_version:
        description: The version of terraform to use. Defaults to the latest
        required: false
        type: string
        default: 'latest'

jobs:
  security:
    name: Terraform Security Analysis
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: tfsec
        uses: tfsec/tfsec-sarif-action@main
        with:
          sarif_file: tfsec.sarif         
          working_directory: ${{ inputs.path }}
          github_token: ${{ secrets.token }}

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: tfsec.sarif
          working_directory: ${{ inputs.path }}
          tfsec_version: ${{ inputs.tfsec_version }}
